/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t  dummy_8bit  = 0;
uint16_t dummy_16bit = 0;
uint32_t dummy_32bit = 0;

uint16_t dummy_16bit_dec  = 0;
uint16_t dummy_16bit_hex = 0;
uint16_t dummy_16bit_bin = 0;

uint8_t overflow_demo = 0;

uint8_t a = 0;
int8_t  b = 0;
int8_t  c = 0;

uint8_t x = 0;
uint8_t y = 0;

uint8_t result;

uint8_t r1 = 0;
uint8_t r2 = 0;
uint8_t r3 = 0;
uint8_t r4 = 0;

uint8_t div_result = 0;
uint8_t mod_result = 0;
uint8_t mul_result = 0;

uint8_t sum = 0 ;
uint8_t val = 3;

uint8_t left1  = 0;
uint8_t left2  = 0;
uint8_t left3  = 0;
uint8_t right1 = 0;

uint8_t desborleft= 0;

uint8_t counter=0;

uint16_t sum2=0;

uint8_t input = 0;
uint8_t output = 0;


int main(void)
{


	dummy_16bit_dec = 32;
    dummy_16bit_hex = 0x20;
    dummy_16bit_bin = 0b100000;

    /*expomiendo el caso overflow
     */

	dummy_8bit = 255;
    dummy_16bit = 255;
    dummy_32bit = 255;

    /*incremento el valor de la variable dummy_8bit en 1 y lo cargo
     * en la varible overflow_demo
     */
    overflow_demo = dummy_8bit + 1;
    overflow_demo = overflow_demo + 1;

    overflow_demo = 735;

    /*declarando variable donde el signo importa*/

    a = 200; /*sera 200*/
    b = 200; /*sera 200*/
    c = -1; /*sera en binario 111111 osea 255 en decimal por lo que en hexa es 0xff*/

    /* aricmetica mental en hexa */

    result = 0x0F + 0x01; /*es 15+1=16 0x10*/
    result = 0xFF + 0x01; /*es 255+1 se desborda osea es 0x00*/
    result = 0xA0 + 0x5F; /*es 160+95=255 osea 0xff*/
    result = 0xA0 + 0x60; /*es 160+96=256 osea se desborda 0x00*/


    /* construyendo bit a bit */

    x = 0x01;
    x = 0x02;
    x = 0x04;
    x = 0x08;
    x = 0x10;
    x = 0x20;
    x = 0x40;
    x = 0x80;

    /*bang y logica boleana*/

    a=5;
    b=0;
    c=255;

    r1 = !a;
    r2 = !b;
    r3 = !c;
    r4 = ~c;

    /*semana 01*/

	/*Operadores aricmeticos*/

	a          = 17; /**/
	b          = 5;
	div_result = a / b;  /*deberia dar 3 con reciduo 2*/
	mod_result = a % b;  /*es el residuo de el de arriba*/
	mul_result = a * b;  /*deberia ser 85*/

	c=div_result*b+mod_result;		/* debe dar el mismo a*/

	/* desbordamiento aricmetico */

	x   = 200;
	y   = 100;
	sum = x + y;

	/* Operadores de desplazamiento como multiplicación y división */

	val=3;

	left1  = val << 1;
	left2  = val << 2;
	left3  = val << 3;
	right1 = val >> 1;

	desborleft = 128;
	desborleft = desborleft << 1;

    /* pruebas de if/else */

	x=3;
    y=0;
    result=0;

    if (x>0){
    	result=255;
    }

    if (x<y){
    result=128;
    }
    else{
    result=0;
    }

    /* El bucle for como contador */

    for(counter=0;counter<9;counter++){

      }

    for(counter=0;counter<8;counter+=2){

    }

    for(counter=10;counter<2;counter--){

      }

    /* bucle while */

    x=1;
    sum=0;

    while (x <= 10) {
        sum += x;
        x++;
    }                   /*es 55*/

    y=1;



    while (y <= 100) {
        sum2 += y;
        y++;
    }                   /*se espera que sea 5050 y no cabria en una variable de uint pues esta tiene un maximo de 255*/

    /* bucle do-while */


        result = 0;
        x = 10;

        while (x < 5) {
            result = 42;
        }                     /*en while se revisa primero elcondicional y si cumple se ejecuta si no no se ejecuta*/

        y = 10;

        do {
            result = 42;
        } while (y < 5);    /* en do-while se ejecuta primero y luego se revisa el condicional */

       /* switch-case */

        input=4;
        output=0;

        switch (input) {

                case 1:
                    output = 10;
                    break;

                case 2:
                    output = 20;
                    break;

                case 3:
                    output = 30;
                    break;

                case 4:
                    output = 40;
                    break;

                default:
                    output = 255;
                    break;
            }



    /* Loop forever */
    while(1){

    }
    return 0;
}
