/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif






int main(void)
{

	/* Operador AND: la máscara que revela */

	uint8_t value  = 0b10110101;
	uint8_t mask   = 0b00001111;
	uint8_t result  = 0b0;

	result = value & mask;

	mask = 0b01111000;
	result = value & mask;



	/* Operador OR: la máscara que establece */

	value  = 0b10100000;
	mask   = 0b00000101;
	result = value | mask;  /* 1 y 1 darian 1, 0 y 0 dan 0 */

    /* Operador NOT: el complemento */

	uint8_t a       = 0b00001111;
	uint8_t result1 = 0b0;
	result1 = ~a;

	uint8_t b       = 0b10100101;
	uint8_t result2 = 0b0;
	result2 = ~b;

	value = 0b11111111;
	value = ~value;        /* este metodo invierte todos los bits */

	value = 0b11111111;
	value &= ~0b00000011;  /* este metodo simplemente invierte los bists seleccionados en ~()  */

	/* Operador XOR: el toggle */

	value   = 0b10110011;
	mask    = 0b00001111;
	result1 = value ^ mask;
	result2 = result1 ^ mask;

	uint8_t ejem = 0b11111110;
	ejem ^= (1 << 2);


	/* Combinando operadores: el patrón completo */


	uint8_t simulated_register = 0x00;

	simulated_register |= 0b00011000;

	simulated_register &= ~0b00010000;

	simulated_register ^= 0b00010000;

	simulated_register ^= 0b00010000;

	/* Primer registro real: habilitando el reloj */

	RCC->AHB1ENR |= (1 << 0);

	/* Primer LED en GPIOA Pin 5 */

	GPIOA->MODER &= ~(3 << 10);
	GPIOA->MODER |=  (1 << 10);

	GPIOA->ODR |= (1 << 5);





    /* Loop forever */
    while(1){

    }
    return 0;
}
