/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif






int main(void)
{

	/* Identificando periféricos en sus buses */

         /*AHB1 TENIA GPIOA(bit 0), GPIOB(bit 1) Y GPIOAC (bit 2), ADEMAS AHB1 NO TIENE NINGUN REGISTRO DE RELOJ DE LOS MENCIONADOS (GPIOA, GPIOB, GPIOC, USART2, TIM2, SPI1) */

	//RCC->AHB1ENR |= (0b111 << 0);
	//RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	     /* APB1 SOLO TENIA A USART2(bit 17) Y TIM2(bit 0) */

	//RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
	//RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

	     /* APB2 SOLO TENIA A SPI1(bit 12) */

	//RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;


	/* Habilitando y deshabilitando relojes de periféricos */

	RCC->AHB1ENR |= (0b11 << 0);

	RCC->AHB1ENR &= ~(0b10 << 0);  /* FUNCIONA :) ESTA VIVO*/

	/* Leyendo el registro MODER */

	//VALOR GPIOA->MODER (0xa8000000)

	GPIOA->MODER &= ~(0b11 << 10); /* PA LIMPIAR */

	GPIOA->MODER |= (0b01 << 10);  /* ACTIVO EL OUTPUT DE SE PIN */

	/* Explorando el conjunto completo de registros GPIO */

	GPIOA->OTYPER = 0x00000000;   /* MATAMOS EL NUMERO Y LO MANDAMOS TODOA CERO */
	GPIOA->OTYPER &= ~(1 << 5);   /* CAMBIAMOS RE CONFIRMAMOS QUE EL bit 5  SEA CERO */

	GPIOA->OSPEEDR = 0x00000000;  /* reseteamos */

	GPIOA->PUPDR = 0x00000000;    /* TAMBIEN RESETEAMOS */

	GPIOA->ODR |= (1 << 5);

	GPIOA->ODR &= ~(1 << 5);


	/*  Configurando un pin de entrada  */

	RCC->AHB1ENR |= (1 << 2);  /* activar reloj */

	GPIOC->MODER &= ~(0b11 << 26); /* poner cero (0) a 27-26, confuguracion input */

	GPIOC->PUPDR &= ~(0b11 << 26); /* EN EL REGISTRO PUPDR TAMBIES ES 27-26 CON ESTO TAMBIEN LO PONEMOS A CERO */
    GPIOC->PUPDR |= (0b1 << 26);   /* MANDAMOS A 1 EL bit 26 configuracion pull-up*/



    /* Loop forever */
    while(1){

    }
    return 0;
}
